-- UNION: DISTINCT VALUE
SELECT *
FROM EMPLOYEES
WHERE SALARY > 15000
UNION
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- UNION ALL: ALL VALUE 
SELECT *
FROM EMPLOYEES
WHERE SALARY > 15000
UNION ALL
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- INTERSECT: COMMON VALUES ONLY
SELECT *
FROM EMPLOYEES
WHERE SALARY > 5000
INTERSECT
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- MINUS mySQL NOT working, use different way to handle it.
SELECT *
FROM EMPLOYEES
WHERE SALARY > 5000 AND DEPARTMENT_ID != 80;

-- Some problem solving (online)
-- 1) https://leetcode.com/problems/duplicate-emails/description/
SELECT email
FROM PERSON
GROUP BY EMAIL
HAVING COUNT(EMAIL) > 1;

-- 2) https://leetcode.com/problems/employees-earning-more-than-their-managers/
SELECT E.NAME AS EMPLOYEE
FROM EMPLOYEE AS E, EMPLOYEE AS M
WHERE E.MANAGERID = M.ID AND E.SALARY > M.SALARY;

-- 3) https://leetcode.com/problems/customers-who-never-order/description/
SELECT CUSTOMERS.NAME AS CUSTOMERS
FROM CUSTOMERS
    LEFT JOIN ORDERS
        ON CUSTOMERS.ID = ORDERS.CUSTOMERID
GROUP BY CUSTOMERS.ID
HAVING COUNT(ORDERS.ID) = 0;