CREATE TABLE STUDENT
(
	ROLL CHAR(6) PRIMARY KEY,
    NAME VARCHAR(60)
);

CREATE TABLE COURSE
(
	C_ID CHAR(6) PRIMARY KEY,
    C_NAME VARCHAR(60)
);

CREATE TABLE ENROLL
(
	ROLL CHAR(6) PRIMARY KEY,
    C_ID CHAR(6),
    FOREIGN KEY(ROLL) REFERENCES STUDENT(ROLL) ON DELETE CASCADE,
    FOREIGN KEY(C_ID) REFERENCES COURSE(C_ID) ON DELETE SET NULL
);