-- QUESTION-1:
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY)
	FROM EMPLOYEES 
	WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES 
		WHERE SALARY < (
			SELECT MAX(SALARY)
			FROM EMPLOYEES 
		)
	)
);

-- QUESTION-2:
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MIN(SALARY)
    FROM EMPLOYEES
    WHERE SALARY > (
		SELECT MIN(SALARY)
        FROM EMPLOYEES 
        WHERE SALARY > (
			SELECT MIN(SALARY)
            FROM EMPLOYEES
		)
    )
);

-- QUESTION- 3
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE > (
	SELECT MIN(HIRE_DATE)
    FROM EMPLOYEES
    WHERE FIRST_NAME = 'Steven'
);

-- QUESTION-4:
WITH MX AS
(
	SELECT MAX(SALARY) MXSAL
	FROM EMPLOYEES 
	WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES 
		WHERE SALARY < (
			SELECT MAX(SALARY)
			FROM EMPLOYEES 
		)
	)
)
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MXSAL FROM MX);

WITH MN AS 
(
	SELECT MIN(SALARY) AS MNSAL
    FROM EMPLOYEES
    WHERE SALARY > (
		SELECT MIN(SALARY)
        FROM EMPLOYEES 
        WHERE SALARY > (
			SELECT MIN(SALARY)
            FROM EMPLOYEES
		)
    )
)
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MNSAL
    FROM MN
);