-- BASIC SUBQUERY START
SELECT * 
FROM EMPLOYEES
WHERE SALARY < (
	SELECT SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 144
);

SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY)
	FROM EMPLOYEES
);

SELECT AVG(SALARY) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID
	FROM DEPARTMENTS
	WHERE DEPARTMENT_NAME = 'MARKETING'
);

SELECT COUNT(*) AS MEMBERS 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
	SELECT DEPARTMENT_ID
	FROM DEPARTMENTS
	WHERE DEPARTMENT_NAME = 'IT'
);

SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = (
	SELECT JOB_ID
    FROM JOBS
    WHERE JOB_TITLE = 'PROGRAMMER'
);
-- BASIC SUBQUERY END

-- ADVANCE SUBQUERY START
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT DISTINCT SALARY
	FROM EMPLOYEES
	ORDER BY SALARY DESC
	LIMIT 1
	OFFSET 1
);

SELECT *
FROM EMPLOYEES
WHERE SALARY = (
	SELECT MAX(SALARY)
	FROM EMPLOYEES 
    WHERE SALARY < (
		SELECT MAX(SALARY)
		FROM EMPLOYEES
	)
);

SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (
	SELECT SALARY
    FROM EMPLOYEES AS MGR
    WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
);

SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (
	SELECT JOB_ID
    FROM EMPLOYEES AS MGR
    WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
);
-- ADVANCE SUBQUERY END

-- COMMON TABLE EXPRESSION START
WITH TMP AS 
(
	SELECT *
    FROM EMPLOYEES
    ORDER BY SALARY
    LIMIT 5
)
SELECT *
FROM TMP;

-- EXAMPLE OF CTE
WITH AVGIT AS
(
	SELECT AVG(SALARY) AS SAL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 60 -- IT
),
MAXMKT AS 
(
	SELECT MAX(SALARY) AS SAL2
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20 -- MARKETING
)
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL1 FROM AVGIT) AND SALARY < (SELECT SAL2 FROM MAXMKT);

-- COMMON TABLE EXPRESSION END